### ISSUE TITLE
Error on startup with Dank Unloader

### ISSUE THREAD

**Issue by mrcoffee1026** [Sefiraat/DankTech2#7]
Getting this error on startup with the Dank Unloader... at which point the machine vanishes (needs replacement).  I can replace it, but the next server restart, the error will repeat and the machine will vanish again:

startup error:
```
[01:15:02] [Server thread/ERROR]: [DankTech2] Item "DK2_UNLOADER_1" from DankTech2 vDEV - 4 (git 803760fb) has caused an Error!
[01:15:02] [Server thread/ERROR]: [DankTech2] You can report it here: https://github.com/Sefiraat/DankTech2/issues/
[01:15:02] [Server thread/ERROR]: [DankTech2] An Error occurred while trying to create a BlockMenu
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.getUniqueId()" because "armorStand" is null
	at io.github.sefiraat.danktech2.slimefun.machines.DankUnloader$2.newInstance(DankUnloader.java:209) ~[DankTech2 - DEV 3 (git cc95b).jar:?]
	at me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.lambda$newInstance$0(BlockMenuPreset.java:258) ~[Slimefun4 - DEV 999 (git e02ee).jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:15:03] [Server thread/ERROR]: [DankTech2] Item "DK2_UNLOADER_1" from DankTech2 vDEV - 4 (git 803760fb) has caused an Error!
[01:15:03] [Server thread/ERROR]: [DankTech2] You can report it here: https://github.com/Sefiraat/DankTech2/issues/
[01:15:03] [Server thread/ERROR]: [DankTech2] An Error occurred while trying to create a BlockMenu
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.getUniqueId()" because "armorStand" is null
	at io.github.sefiraat.danktech2.slimefun.machines.DankUnloader$2.newInstance(DankUnloader.java:209) ~[DankTech2 - DEV 3 (git cc95b).jar:?]
	at me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.lambda$newInstance$0(BlockMenuPreset.java:258) ~[Slimefun4 - DEV 999 (git e02ee).jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

date.err:
https://pastebin.com/g2kCbM7h

**Comment by Sefiraat** [comment]
I have a fix - ill get it out asap :)

**Comment by mrcoffee1026** [comment]
Thanks so much!

**Comment by JasperChaseTOQ** [comment]
any update on this cause its still an ongoing issue i believe
